# MIT License
#
# Copyright (c) 2025 Andrew Symington
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Docker Compose Spec Version
# See: https://docs.docker.com/compose/compose-file/compose-versioning/#version-3

services:
  libsurvive_ros2:
    build: .
    network_mode: host
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    user: root
    volumes:
      - ./calibration:/root/.config/libsurvive
      - ./entrypoint_recalibrate.sh:/entrypoint_recalibrate.sh:ro
    entrypoint: /entrypoint_recalibrate.sh
    working_dir: /home/ros/ros2_ws
    command: ros2 launch libsurvive_ros2 libsurvive_ros2.launch.py rosbridge:=true foxbridge:=true composable:=false
    environment:
      - RECALIBRATE=${RECALIBRATE:-false}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}